apiVersion: v1
kind: ConfigMap
metadata:
  name: asterisk-configmap
data:
  DOMAIN: "asterisk.docker.local"
  MYSQL_DB: "asterisk"
  MYSQL_USER: "asterisk"
  MYSQL_PASSWORD: "asterisk"
  LANG: "ru_RU.utf8"
  LC_ALL: "ru_RU.utf8"
  LANGUAGE: "ru_RU.utf8"
  TZ: "Asia/Tehran"